name: Auto Update JSON and M3U (ZIP Protected - Every 10 min)

on:
  schedule:
    - cron: '*/10 * * * *'  # প্রতি ১০ মিনিট পরপর চালাবে

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: |
          echo "${{ secrets.ZIP_PASSWORD }}" > zip_pass.txt
          unzip -P "$(cat zip_pass.txt)" run.zip
          rm zip_pass.txt

      - name: Run Python Script
        run: python run.py

      - name: Delete Script After Run
        run: rm -f run.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add NS_player.json ALL.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update NS_player.json and ALL.m3u"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write
