name: Trigger Runner Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Runner Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/run.yml/dispatches \
            -d '{"ref":"main"}'
